raw_data = [
    ("May 26, 1896", "The American Cotton Oil Company", "Added"),
    ("May 26, 1896", "Distilling & Cattle Feeding Co.", "Added"),
    ("May 26, 1896", "North American Company", "Added"),
    ("May 26, 1896", "The American Sugar Refining Company", "Added"),
    ("May 26, 1896", "General Electric Company", "Added"),
    ("May 26, 1896", "Tennessee Coal, Iron and Railroad Company", "Added"),
    ("May 26, 1896", "American Tobacco Company", "Added"),
    ("May 26, 1896", "The Laclede Gas Company", "Added"),
    ("May 26, 1896", "The United States Leather Company (Preferred)", "Added"),
    ("May 26, 1896", "Chicago Gas Light and Coke Company", "Added"),
    ("May 26, 1896", "National Lead Company", "Added"),
    ("May 26, 1896", "United States Rubber Company", "Added"),

    ("August 26, 1896", "United States Cordage Company (Preferred)", "Added"),
    ("August 26, 1896", "North American Company", "Removed"),
    ("August 26, 1896", "Distilling & Cattle Feeding Co.", "Renamed", "Renamed to American Spirits Manufacturing Co."),

    ("November 10, 1896", "Pacific Mail Steamship Company", "Added"),
    ("November 10, 1896", "United States Rubber Company", "Removed"),

    ("December 23, 1896", "Standard Rope & Twine Co.", "Added"),
    ("December 23, 1896", "United States Cordage Company (Preferred)", "Removed"),

    ("March 24, 1898", "Peoples Gas", "Added"),
    ("March 24, 1898", "Chicago Gas Light and Coke Company", "Removed"),

    ("September 1, 1898", "United States Rubber Company", "Added"),
    ("September 1, 1898", "General Electric Company", "Removed"),
    ("September 1, 1898", "Peoples Gas", "Renamed", "Renamed to The Peoples Gas Light and Coke Company."),

    ("April 21, 1899", "American Spirits Manufacturing Co.", "Removed"),
    ("April 21, 1899", "The Laclede Gas Company", "Removed"),
    ("April 21, 1899", "Standard Rope & Twine Co.", "Removed"),
    ("April 21, 1899", "American Tobacco Company", "Removed"),
    ("April 21, 1899", "Federal Steel Company", "Added"),
    ("April 21, 1899", "American Steel & Wire Co.", "Added"),
    ("April 21, 1899", "General Electric Company", "Added"),
    ("April 21, 1899", "Continental Tobacco Company", "Added"),

    ("April 1, 1901", "Amalgamated Copper Mining Company", "Added"),
    ("April 1, 1901", "International Paper Company (Preferred)", "Added"),
    ("April 1, 1901", "American Smelting & Refining Company", "Added"),
    ("April 1, 1901", "United States Steel Corporation", "Added"),
    ("April 1, 1901", "United States Steel Corporation (Preferred)", "Added"),
    ("April 1, 1901", "The American Cotton Oil Company", "Removed"),
    ("April 1, 1901", "Federal Steel Company", "Removed"),
    ("April 1, 1901", "Pacific Mail Steamship Company", "Removed"),
    ("April 1, 1901", "American Steel & Wire Co.", "Removed"),
    ("April 1, 1901", "General Electric Company", "Removed"),

    ("July 1, 1901", "Colorado Fuel and Iron Company", "Added"),
    ("July 1, 1901", "American Car and Foundry Company", "Added"),
    ("July 1, 1901", "Continental Tobacco Company", "Removed"),
    ("July 1, 1901", "International Paper Company (Preferred)", "Removed"),

    ("April 1, 1905", "United States Rubber Company (First Preferred)", "Added"),
    ("April 1, 1905", "The United States Leather Company (Preferred)", "Removed"),

    ("November 7, 1907", "General Electric Company", "Added"),
    ("November 7, 1907", "Tennessee Coal, Iron and Railroad Company", "Removed"),

    ("May 12, 1912", "Central Leather Company", "Added"),
    ("May 12, 1912", "Colorado Fuel and Iron Company", "Removed"),

    ("March 16, 1915", "General Motors Corporation", "Added"),
    ("March 16, 1915", "United States Rubber Company (First Preferred)", "Removed"),

    ("July 29, 1915", "Amalgamated Copper Mining Company", "Renamed", "Renamed to Anaconda Copper Mining Company"),

    ("October 4, 1916", "The American Beet Sugar", "Added"),
    ("October 4, 1916", "The Texas Company", "Added"),
    ("October 4, 1916", "American Can Company", "Added"),
    ("October 4, 1916", "The Baldwin Locomotive Works", "Added"),
    ("October 4, 1916", "American Locomotive Company", "Added"),
    ("October 4, 1916", "Utah Copper Company", "Added"),
    ("October 4, 1916", "B.F. Goodrich Corporation", "Added"),
    ("October 4, 1916", "Western Union Company", "Added"),
    ("October 4, 1916", "Republic Iron and Steel Company", "Added"),
    ("October 4, 1916", "Westinghouse Electric Corporation", "Added"),
    ("October 4, 1916", "American Telephone and Telegraph Company", "Added"),
    ("October 4, 1916", "Studebaker Corporation", "Added"),
    ("October 4, 1916", "General Motors Corporation", "Removed"),
    ("October 4, 1916", "National Lead Company", "Removed"),
    ("October 4, 1916", "The Peoples Gas Light and Coke Company", "Removed"),
    ("October 4, 1916", "United States Steel Corporation (Preferred)", "Removed"),

    ("March 1, 1920", "Corn Products Refining Company", "Added"),
    ("March 1, 1920", "The American Beet Sugar", "Removed"),

    ("January 22, 1924", "E.I. du Pont de Nemours & Company", "Added"),
    ("January 22, 1924", "Mack Trucks, Inc.", "Added"),
    ("January 22, 1924", "American Tobacco Company (B shares)", "Added"),
    ("January 22, 1924", "Sears Roebuck & Company", "Added"),
    ("January 22, 1924", "Central Leather Company", "Removed"),
    ("January 22, 1924", "B.F. Goodrich Corporation", "Removed"),
    ("January 22, 1924", "The Texas Company", "Removed"),
    ("January 22, 1924", "Corn Products Refining Company", "Removed"),

    ("February 6, 1924", "Standard Oil Co. (California)", "Added"),
    ("February 6, 1924", "Utah Copper Company", "Removed"),

    ("May 12, 1924", "F. W. Woolworth Company", "Added"),
    ("May 12, 1924", "Republic Iron and Steel Company", "Removed"),

    ("August 31, 1925", "United States Realty and Construction Company", "Added"),
    ("August 31, 1925", "General Motors Corporation", "Added"),
    ("August 31, 1925", "International Harvester Company", "Added"),
    ("August 31, 1925", "Kennecott Mines Company", "Added"),
    ("August 31, 1925", "The Texas Company", "Added"),
    ("August 31, 1925", "Anaconda Copper Mining Company", "Removed"),
    ("August 31, 1925", "E.I. du Pont de Nemours & Company", "Removed"),
    ("August 31, 1925", "Standard Oil Co. (California)", "Removed"),
    ("August 31, 1925", "The Baldwin Locomotive Works", "Removed"),
    ("August 31, 1925", "Studebaker Corporation", "Removed"),

    ("December 7, 1925", "Allied Chemical and Dye Corporation", "Added"),
    ("December 7, 1925", "Paramount Famous Lasky Corporation", "Added"),
    ("December 7, 1925", "United States Realty and Construction Company", "Removed"),
    ("December 7, 1925", "Westinghouse Electric Corporation", "Removed"),

    ("December 31, 1925", "Remington Typewriter Company", "Added"),
    ("December 31, 1925", "Kennecott Mines Company", "Removed"),

    ("March 16, 1927", "United Drug Stores", "Added"),
    ("March 16, 1927", "Remington Typewriter Company", "Removed"),

    ("October 1, 1928", "General Railway Signal Company", "Added"),
    ("October 1, 1928", "B.F. Goodrich Corporation", "Added"),
    ("October 1, 1928", "Standard Oil Co. of New Jersey", "Added"),
    ("October 1, 1928", "International Nickel Company, Ltd.", "Added"),
    ("October 1, 1928", "Texas Gulf Sulphur Company", "Added"),
    ("October 1, 1928", "Union Carbide Corporation", "Added"),
    ("October 1, 1928", "Atlantic Refining Company", "Added"),
    ("October 1, 1928", "Nash Motors Company", "Added"),
    ("October 1, 1928", "Bethlehem Steel Corporation", "Added"),
    ("October 1, 1928", "North American Company", "Added"),
    ("October 1, 1928", "Victor Talking Machine Company", "Added"),
    ("October 1, 1928", "Chrysler Corporation", "Added"),
    ("October 1, 1928", "Paramount Famous Lasky Corporation ", "Renamed", "Renamed to Paramount Publix Corporation"),
    ("October 1, 1928", "Westinghouse Electric Corporation", "Added"),
    ("October 1, 1928", "Postum Incorporated", "Added"),
    ("October 1, 1928", "Radio Corporation of America", "Added"),
    ("October 1, 1928", "Wright Aeronautical", "Added"),
    ("October 1, 1928", "American Car and Foundry Company", "Removed"),
    ("October 1, 1928", "American Telephone and Telegraph Company", "Removed"),
    ("October 1, 1928", "United States Rubber Company", "Removed"),
    ("October 1, 1928", "American Locomotive Company", "Removed"),
    ("October 1, 1928", "United Drug Stores", "Removed"),
    ("October 1, 1928", "Western Union Company", "Removed"),

    ("January 8, 1929", "National Cash Register Company", "Added"),
    ("January 8, 1929", "Victor Talking Machine Company", "Removed"),

    ("September 14, 1929", "Postum Incorporated", "Renamed", "Renamed to General Foods Corporation"),
    ("September 14, 1929", "Wright Aeronautical", "Renamed", "Renamed to Curtiss-Wright Corporation"),

    ("January 29, 1930", "Johns-Manville Corporation", "Added"),
    ("January 29, 1930", "North American Company", "Removed"),

    ("July 18, 1930", "Goodyear Tire and Rubber Company", "Added"),
    ("July 18, 1930", "Hudson Motor Car Company", "Added"),
    ("July 18, 1930", "Standard Oil Co. of California", "Added"),
    ("July 18, 1930", "Borden, Inc.", "Added"),
    ("July 18, 1930", "Liggett & Myers Tobacco Company", "Added"),
    ("July 18, 1930", "Eastman Kodak Company", "Added"),
    ("July 18, 1930", "United Aircraft and Transport Corporation", "Added"),
    ("July 18, 1930", "The American Sugar Refining Company", "Removed"),
    ("July 18, 1930", "Curtiss-Wright Corporation", "Removed"),
    ("July 18, 1930", "B.F. Goodrich Corporation", "Removed"),
    ("July 18, 1930", "American Tobacco Company (B shares)", "Removed"),
    ("July 18, 1930", "General Railway Signal Company", "Removed"),
    ("July 18, 1930", "Nash Motors Company", "Removed"),
    ("July 18, 1930", "Atlantic Refining Company", "Removed"),

    ("May 26, 1932", "Nash Motors Company", "Added"),
    ("May 26, 1932", "The Procter & Gamble Company", "Added"),
    ("May 26, 1932", "American Tobacco Company (B shares)", "Added"),
    ("May 26, 1932", "International Business Machines", "Added"),
    ("May 26, 1932", "The Coca-Cola Company", "Added"),
    ("May 26, 1932", "International Shoe Company", "Added"),
    ("May 26, 1932", "Drug Incorporated", "Added"),
    ("May 26, 1932", "Loew's Theatres Incorporated", "Added"),
    ("May 26, 1932", "Hudson Motor Car Company", "Removed"),
    ("May 26, 1932", "National Cash Register Company", "Removed"),
    ("May 26, 1932", "Texas Gulf Sulphur Company", "Removed"),
    ("May 26, 1932", "Liggett & Myers Tobacco Company", "Removed"),
    ("May 26, 1932", "Paramount Publix Corporation", "Removed"),
    ("May 26, 1932", "United Aircraft and Transport Corporation", "Removed"),
    ("May 26, 1932", "Mack Trucks, Inc.", "Removed"),
    ("May 26, 1932", "Radio Corporation of America", "Removed"),

    ("August 15, 1933", "United Aircraft and Transport Corporation", "Added"),
    ("August 15, 1933", "Corn Products Refining Company", "Added"),
    ("August 15, 1933", "Drug Incorporated", "Removed"),
    ("August 15, 1933", "International Shoe Company", "Removed"),

    ("August 13, 1934", "National Distillers Products Corporation", "Added"),
    ("August 13, 1934", "United Aircraft and Transport Corporation", "Removed"),

    ("November 20, 1935", "National Steel Corporation", "Added"),
    ("November 20, 1935", "E.I. du Pont de Nemours & Company", "Added"),
    ("November 20, 1935", "Borden, Inc.", "Removed"),
    ("November 20, 1935", "The Coca-Cola Company", "Removed"),

    ("March 4, 1939", "American Telephone and Telegraph Company", "Added"),
    ("March 4, 1939", "United Aircraft Corporation", "Added"),
    ("March 4, 1939", "International Business Machines", "Removed"),
    ("March 4, 1939", "Nash Motors Company", "Removed"),

    ("July 3, 1956", "International Paper Company", "Added"),
    ("July 3, 1956", "Loew's Theatres Incorporated", "Removed"),

    ("June 1, 1959", "Aluminum Company of America", "Added"),
    ("June 1, 1959", "Swift & Company", "Added"),
    ("June 1, 1959", "Anaconda Copper Mining Company", "Added"),
    ("June 1, 1959", "Owens-Illinois, Inc.", "Added"),
    ("June 1, 1959", "Allied Chemical and Dye Corporation", "Renamed", "Renamed to Allied Chemical Corporation"),
    ("June 1, 1959", "The Texas Company", "Renamed", "Renamed to Texaco Incorporated"),
    ("June 1, 1959", "American Smelting & Refining Company", "Removed"),
    ("June 1, 1959", "National Distillers Products Corporation", "Removed"),
    ("June 1, 1959", "National Steel Corporation", "Removed"),
    ("June 1, 1959", "Corn Products Refining Company", "Removed"),

    ("August 9, 1976", "Minnesota Mining & Manufacturing Company", "Added"),
    ("August 9, 1976", "Anaconda Copper Mining Company", "Removed"),
    ("August 9, 1976", "Standard Oil Co. of New Jersey", "Renamed", "Renamed to Exxon Corporation"),
    ("August 9, 1976", "International Nickel Company, Ltd", "Renamed", "Renamed to Inco Limited"),
    ("August 9, 1976", "United Aircraft Corporation", "Renamed", "Renamed to United Technologies Corporation"),
    ("August 9, 1976", "Swift & Company", "Renamed", "Renamed to Esmark Corporation"),

    ("June 29, 1979", "International Business Machines", "Added"),
    ("June 29, 1979", "Merck & Co., Inc.", "Added"),
    ("June 29, 1979", "Chrysler Corporation", "Removed"),
    ("June 29, 1979", "Esmark Corporation", "Removed"),

    ("August 30, 1982", "American Express Company", "Added"),
    ("August 30, 1982", "Johns-Manville Corporation", "Removed"),

    ("October 30, 1985", "Philip Morris Companies Inc", "Added"),
    ("October 30, 1985", "McDonald's Corporation", "Added"),
    ("October 30, 1985", "American Tobacco Company (B shares)", "Removed"),
    ("October 30, 1985", "General Foods Corporation", "Removed"),
    ("October 30, 1985", "Allied Chemical Corporation", "Renamed", "Renamed to Allied-Signal Incorporated"),
    ("October 30, 1985", "Standard Oil Co. of California", "Renamed", "Renamed to Chevron Corporation"),

    ("March 12, 1987", "International Harvester Company", "Renamed", "Renamed to Navistar International Corporation"),
    ("March 12, 1987", "United States Steel Corporation", "Renamed", "Renamed to USX Corporation "),
    ("March 12, 1987", "The Boeing Company", "Added"),
    ("March 12, 1987", "The Coca-Cola Company", "Added"),
    ("March 12, 1987", "Inco Limited", "Removed"),
    ("March 12, 1987", "Owens-Illinois, Inc.", "Removed"),

    ("May 6, 1991", "American Telephone and Telegraph Company", "Renamed", "Renamed to AT&T Corporation"),
    ("May 6, 1991", "Caterpillar Inc.", "Added"),
    ("May 6, 1991", "J.P. Morgan & Company", "Added"),
    ("May 6, 1991", "The Walt Disney Company", "Added"),
    ("May 6, 1991", "American Can Company", "Removed"),
    ("May 6, 1991", "Navistar International Corporation", "Removed"),
    ("May 6, 1991", "USX Corporation", "Removed"),

    ("March 17, 1997", "Hewlett-Packard Company", "Added"),
    ("March 17, 1997", "Travelers Inc.", "Added"),
    ("March 17, 1997", "Johnson & Johnson", "Added"),
    ("March 17, 1997", "Wal-Mart Stores, Inc.", "Added"),
    ("March 17, 1997", "Bethlehem Steel Corporation", "Removed"),
    ("March 17, 1997", "Westinghouse Electric Corporation", "Removed"),
    ("March 17, 1997", "F. W. Woolworth Company", "Removed"),
    ("March 17, 1997", "Texaco Incorporated", "Removed"),

    ("November 1, 1999", "Aluminum Company of America", "Renamed", "Renamed to Alcoa Inc"),
    ("November 1, 1999", "Travelers Inc", "Renamed", "Renamed to Citigroup Inc"),
    ("November 1, 1999", "Microsoft Corporation", "Added"),
    ("November 1, 1999", "The Home Depot, Inc.", "Added"),
    ("November 1, 1999", "Intel Corporation", "Added"),
    ("November 1, 1999", "SBC Communications Inc.", "Added"),
    ("November 1, 1999", "Chevron Corporation", "Removed"),
    ("November 1, 1999", "Sears Roebuck & Company", "Removed"),
    ("November 1, 1999", "Union Carbide Corporation", "Removed"),
    ("November 1, 1999", "Goodyear Tire and Rubber Company", "Removed"),

    ("January 27, 2003", "Minnesota Mining & Manufacturing Company", "Renamed", "Renamed to 3M Company"),
    ("January 27, 2003", "Exxon Corporation", "Renamed", "Renamed to Exxon Mobil Corporation "),
    ("January 27, 2003", "J.P. Morgan & Company", "Renamed", "Renamed to JPMorgan Chase & Co.."),
    ("January 27, 2003", "Philip Morris Companies Inc", "Renamed", "Renamed to Altria Group."),
    ("January 27, 2003", "Allied-Signal Incorporated", "Renamed", "Renamed to Honeywell International."),

    ("April 8, 2004", "Pfizer Inc.", "Added"),
    ("April 8, 2004", "American International Group, Inc.", "Added"),
    ("April 8, 2004", "Verizon Communications Inc.", "Added"),
    ("April 8, 2004", "AT&T Corporation", "Removed"),
    ("April 8, 2004", "Eastman Kodak Company", "Removed"),
    ("April 8, 2004", "International Paper Company", "Removed"),

    ("November 21, 2005", "SBC Communications Inc", "Renamed", "Renamed to AT&T Inc."),

    ("February 19, 2008", "Bank of America Corporation", "Added"),
    ("February 19, 2008", "Chevron Corporation", "Added"),
    ("February 19, 2008", "Altria Group, Inc.", "Removed"),
    ("February 19, 2008", "Honeywell International.", "Removed"),

    ("September 22, 2008", "Kraft Foods Inc.", "Added"),
    ("September 22, 2008", "American International Group, Inc.", "Removed"),

    ("June 8, 2009", "The Travelers Companies, Inc.", "Added"),
    ("June 8, 2009", "Cisco Systems, Inc.", "Added"),
    ("June 8, 2009", "Citigroup Inc.", "Removed"),
    ("June 8, 2009", "General Motors Corporation", "Removed"),

    ("September 24, 2012", "UnitedHealth Group Incorporated", "Added"),
    ("September 24, 2012", "Kraft Foods Inc.", "Removed"),

    ("September 23, 2013", "Nike, Inc.", "Added"),
    ("September 23, 2013", "The Goldman Sachs Group, Inc.", "Added"),
    ("September 23, 2013", "Visa Inc.", "Added"),
    ("September 23, 2013", "Alcoa Inc.", "Removed"),
    ("September 23, 2013", "Bank of America Corporation", "Removed"),
    ("September 23, 2013", "Hewlett-Packard Company", "Removed"),

    ("March 19, 2015", "Apple Inc.", "Added"),
    ("March 19, 2015", "AT&T Inc.", "Removed"),

    ("September 1, 2017", "E.I. du Pont de Nemours & Company", "Renamed", "Renamed to DowDuPont Inc."),

    ("June 26, 2018", "Wal-Mart Stores, Inc", "Renamed", "Renamed to Walmart Inc."),
    ("June 26, 2018", "Walgreens Boots Alliance, Inc.", "Added"),
    ("June 26, 2018", "General Electric Company", "Removed"),

    ("April 2, 2019", "Dow Inc.", "Added"),
    ("April 2, 2019", "DowDuPont Inc.", "Removed"),

    ("April 6, 2020", "Raytheon Technologies Corporation", "Added"),
    ("April 6, 2020", "United Technologies Corporation", "Removed"),

    ("August 31, 2020", "Amgen Inc.", "Added"),
    ("August 31, 2020", "Honeywell International Inc.", "Added"),
    ("August 31, 2020", "Salesforce, Inc.", "Added"),
    ("August 31, 2020", "Exxon Mobil Corporation", "Removed"),
    ("August 31, 2020", "Pfizer Inc.", "Removed"),
    ("August 31, 2020", "Raytheon Technologies Corporation", "Removed"),

    ("February 26, 2024", "Amazon.com, Inc.", "Added"),
    ("February 26, 2024", "Walgreens Boots Alliance, Inc.", "Removed"),

    ("November 8, 2024", "Nvidia Corporation", "Added"),
    ("November 8, 2024", "The Sherwin-Williams Company", "Added"),
    ("November 8, 2024", "Dow Inc.", "Removed"),
    ("November 8, 2024", "Intel Corporation", "Removed"),

]